version: "3.9"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: web
    depends_on:
      - api
    ports:
      - "8080:8080"
    restart: unless-stopped
