name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  api:
    name: Backend (NestJS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: api/package-lock.json   
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present -- --ci
      - run: npm run build --if-present

  frontend:
    name: Frontend (React/Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json  
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present -- --ci
      - run: npm run build --if-present